### ISSUE TITLE
Some of the results in the paper, from the estimation of (PI→B), do not replicate

### ISSUE THREAD

**Issue by phl43** [ubcecon/covid-impact#8]
I downloaded the code because I was interested in running a few sensitivity analyses and I noticed that some of the results in the paper do not replicate.

I first noticed that the total effect given by adding π from (BPI→Y) to α from (BPI→Y) times β from (PI→B) (respectively column 3, 1 and 2 of tables 6-9) was equal to the total effect obtained by estimating (BPI→Y) directly (column 4 of tables 6-9) for all policies in all specifications, which is not the case in the tables in the paper that was published.

Then I noticed that it was because, in the results I get when I run the code on my computer, the indirect effect given by α from (BPI→Y) times β from (PI→B) (column 2 of tables 6-9) was not the same as in the paper. In turn, this seems to be because the estimation of (PI→B) doesn't yield the same results when I run the code on my computer as when you did for the results you published in the paper, since the coefficients in table 3 are different.

Do you have any idea what explains this discrepancy? I checked your code in case I could find a mistake, but everything seems fine. I was thinking that perhaps the data had changed since you estimated the model for the paper, but I have no idea and I'd like to make sure that I'm not missing something here.

**Comment by schrimpf** [comment]
Thanks for noticing this. I think the current code is correct. The table in the paper has a mistake. Basically, the PI->B table in the paper has month entering linearly as an integer, instead of month dummies. The current code accidentally fixed this problem. 

## Longer explanation 

There was an update to `plm` between when we finished the paper and when we used renv to pin dependencies. This update forced a change in the `panellag` function in utils.R. The code was doing something like:
```r
f <- as.factor(c(1,2,3))
lagf <- c(NA, f[2:3])
```
which results in `lagf` being an integer instead of a factor. The updated code does something like:
```r
f <- as.factor(c(1,2,3))
lagf <- c(NA, as.vector(f[2:3]))
```
which results in `lagf` being a character, which gets treated as a factor in formulas, and so happens to do what we intended. 
```

**Comment by phl43** [comment]
Thanks, I will check if I can reproduce this on my computer, but it makes sense. Do you know how much it affects the results? My impression was that it didn't result in any dramatic changes, but I haven't investigated the matter very closely and, in any case, it's probably still worth issuing a correction to make sure the paper has the correct tables.
